server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  cloud:
    gateway:
      routes:
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licensing-service/license/{licenseId}
          filters:
            - RewritePath=/licensing-service/license/(?<licenseId>.*), /v1/organization/$\{licenseId}/license/


         
management:
  endpoint:
    gateway:
      enabled: true 
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.optimagrowth.gateway.filters: DEBUG
